name: Build and test

on:
  workflow_dispatch:
  push:

jobs:
  build-base-image:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "TAG=test" >> $GITHUB_ENV
      - name: Config tag for main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "TAG=stable" >> $GITHUB_ENV
      - name: Config tag for dev
        if: ${{ github.ref == 'refs/heads/dev' }}
        run: |
          echo "TAG=latest" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run test
